### ISSUE TITLE
凸報告で現ボスがわかるようにする

### ISSUE THREAD

**Issue by mazarashi** [beroba/convex-management#33]
凸報告を行うとBOTが0～5のリアクションを送信
殴ったボスの番号のリアクションを送信
追加で、0はボス撃破時に送信→次ボスに移動

**Comment by smicle** [comment]
リアクションではなくメッセージ送信時に付け足して欲しい

**Comment by smicle** [comment]
ボスを倒した際に #凸報告 に次のボスの英語を入力して貰う方向性？

**Comment by smicle** [comment]
#凸報告 に現在のボスと周回数を打って貰う方向にしたい
ミスったときにリカバリーがしやすい

**Comment by smicle** [comment]
#20

**Comment by smicle** [comment]
`a 23` のようにボスの番号と周回数を指定して入力するとbotがそのボスだと認識するようにする

**Comment by smicle** [comment]
持ち越しが発生したら自動でボスが切り替わるようにして現在のボスを#凸報告に表示するので確認して貰う

**Comment by smicle** [comment]
ボスの変更を凸報告でできるようにはしない
