### ISSUE TITLE
全凸（90凸）終了時に周回数と現ボスの情報が欲しい

### ISSUE THREAD

**Issue by mazarashi** [beroba/convex-management#45]
ほしい
凸漏れ報告漏れ発生したら機能しなくなるのでなくてもいいかも

**Comment by smicle** [comment]
最終的なスプレッドシートの情報見れば分かるはず

**Comment by smicle** [comment]
```
2日目の全凸終了よ！
現在のボスはワイバーンの23週目
```
みたいにすればいいか

**Comment by mazarashi** [comment]
それが欲しいけど凸漏れ報告漏れ発生したらどうしようもないからなあ…
朝5時に起きている人が手動入力しなきゃならない

**Comment by smicle** [comment]
朝5時10分になって全員の凸終わってない場合に、#凸状況 に報告すれば良さそう
